[phases.setup]
nixPkgs = [
  "glib",
  "nss",
  "nspr",
  "atk",
  "at-spi2-atk",
  "cups",
  "libdrm",
  "dbus",
  "libxkbcommon",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "mesa",
  "alsa-lib",
]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install uv",
  "uv sync --frozen",
  "uv run playwright install chromium",
]

[phases.build]
cmds = ["uv run alembic upgrade head"]
