"""add fecha_recibido to ingresos

Revision ID: 95bcd6db4d8c
Revises: 9b7694c1ae43
Create Date: 2026-07-28 18:50:01.966053

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95bcd6db4d8c'
down_revision: str | None = '9b7694c1ae43'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingresos', sa.Column('fecha_recibido', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingresos', 'fecha_recibido')
    # ### end Alembic commands ###
