"""add referencia and fecha_recibido to egresos

Revision ID: 99b0bf736434
Revises: 95bcd6db4d8c
Create Date: 2026-07-28 20:09:58.921595

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99b0bf736434'
down_revision: str | None = '95bcd6db4d8c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('egresos', sa.Column('referencia', sa.String(), nullable=True))
    op.add_column('egresos', sa.Column('fecha_recibido', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'egresos', ['referencia'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'egresos', type_='unique')
    op.drop_column('egresos', 'fecha_recibido')
    op.drop_column('egresos', 'referencia')
    # ### end Alembic commands ###
