"""tiquetera_numero_fisico_varchar

Revision ID: 9b7694c1ae43
Revises: 0002
Create Date: 2026-07-28 01:40:57.727081

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b7694c1ae43'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tiqueteras', 'numero_fisico',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tiqueteras', 'numero_fisico',
               existing_type=sa.String(length=50),
               type_=sa.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
