"""add categorias_egreso and gastos_recurrentes tables

Revision ID: ff243581ce06
Revises: 99b0bf736434
Create Date: 2026-07-28 21:19:42.909934

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import garay.infraestructura.persistencia.tipos


# revision identifiers, used by Alembic.
revision: str = 'ff243581ce06'
down_revision: str | None = '99b0bf736434'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_egreso',
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('nombre')
    )
    op.create_table('gastos_recurrentes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('monto', garay.infraestructura.persistencia.tipos.TipoDinero(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('dia_mes', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gastos_recurrentes')
    op.drop_table('categorias_egreso')
    # ### end Alembic commands ###
