"""One-off backfill: populate destinatario on existing automatic egresos.

Automatic egresos (tipo='automatico') captured before Slice 1 carry NULL in
the new `destinatario` column.  Their `descripcion` was generated by the live
parser using known f-string templates, so the value can be reconstructed via
reverse-regex — deterministically, no fabrication.

Pattern table (evaluated in order; FIRST match wins):
  1. "Transferencia a cuenta *{digits}"  ->  "*{digits}"   (Bancolombia account)
  2. "Transferencia a {nombre}"          ->  nombre        (Bancolombia Bre-B)
  3. "Compra en {comercio}"              ->  comercio      (Bancolombia debit)
  4. "Envio a {nombre}"                  ->  nombre        (Nequi Bre-B)
  5. "Pago en {comercio}"               ->  comercio      (Nequi commerce)
  6. "Pago PSE a {empresa}"             ->  empresa       (PSE)
  Skip-list (no recipient by design):
     "Pago factura Nequi"               ->  None

Non-matching rows are LEFT NULL — never fabricated.

Usage:
    # Dry-run (default) — reads only, prints report:
    railway run -- uv run python scripts/backfill_destinatario_egresos.py

    # Apply — writes changes inside a transaction:
    railway run -- uv run python scripts/backfill_destinatario_egresos.py --apply
"""

from __future__ import annotations

import argparse
import os
import re

from sqlalchemy import create_engine, text

# ---------------------------------------------------------------------------
# Reverse-regex patterns (ordered — MUST evaluate cuenta before nombre)
# Each tuple: (pattern, group_index, label)
# ---------------------------------------------------------------------------

# Pattern 1: Bancolombia account transfer — "Transferencia a cuenta *{digits}"
# The live parser emits: f"Transferencia a cuenta *{cuenta}" where cuenta is
# all digits (no asterisk in the capture group, asterisk prepended by the parser).
_PATRON_CUENTA = re.compile(r"^Transferencia a cuenta (\*\d+)$")

# Pattern 2: Bancolombia Bre-B — "Transferencia a {nombre}"
# Uses a negative lookahead so "Transferencia a cuenta *..." doesn't fall here.
_PATRON_TRANSFERENCIA = re.compile(r"^Transferencia a (?!cuenta \*\d)(.+)$")

# Pattern 3: Bancolombia debit purchase — "Compra en {comercio}"
_PATRON_COMPRA = re.compile(r"^Compra en (.+)$")

# Pattern 4: Nequi Bre-B — "Envio a {nombre}"
_PATRON_ENVIO = re.compile(r"^Envio a (.+)$")

# Pattern 5: Nequi commerce — "Pago en {comercio}"
_PATRON_PAGO_EN = re.compile(r"^Pago en (.+)$")

# Pattern 6: PSE — "Pago PSE a {empresa}"
_PATRON_PSE = re.compile(r"^Pago PSE a (.+)$")

# Ordered list for extraction loop
_PATRONES: list[tuple[re.Pattern[str], int, str]] = [
    (_PATRON_CUENTA, 1, "Transferencia a cuenta *N"),
    (_PATRON_TRANSFERENCIA, 1, "Transferencia a {nombre}"),
    (_PATRON_COMPRA, 1, "Compra en {comercio}"),
    (_PATRON_ENVIO, 1, "Envio a {nombre}"),
    (_PATRON_PAGO_EN, 1, "Pago en {comercio}"),
    (_PATRON_PSE, 1, "Pago PSE a {empresa}"),
]

# Descriptions that intentionally have no recipient — skip without fabricating.
_SKIP_LIST: frozenset[str] = frozenset(
    {
        "Pago factura Nequi",
    }
)


def extraer_destinatario(descripcion: str) -> str | None:
    """Reverse-parse a parser-generated descripcion into its destinatario.

    Returns the extracted string (never ``""``) or ``None`` when the
    description is not parseable or belongs to the skip-list.

    This function is pure and deterministic — identical input always yields
    identical output, making the backfill safe to re-run.
    """
    desc = descripcion.strip()
    if not desc:
        return None

    if desc in _SKIP_LIST:
        return None

    for patron, grupo, _ in _PATRONES:
        m = patron.match(desc)
        if m:
            valor = m.group(grupo).strip()
            return valor or None  # anti-"" guard

    return None


# ---------------------------------------------------------------------------
# Runner
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--apply",
        action="store_true",
        help="persist changes to the database (default: dry-run, read-only)",
    )
    args = parser.parse_args()

    database_url = os.environ["GARAY_DATABASE_URL"]
    engine = create_engine(database_url, future=True)

    with engine.begin() as conn:
        # Select automatic egresos with NULL destinatario only.
        # Idempotency is enforced at the SQL level: rows already filled are
        # never touched because they won't be in this result set.
        rows = conn.execute(
            text(
                "SELECT id, descripcion "
                "FROM egresos "
                "WHERE destinatario IS NULL AND tipo = 'automatico' "
                "ORDER BY fecha_egreso"
            )
        ).fetchall()

        total_candidatos = len(rows)

        # Build update plan
        actualizaciones: list[tuple[object, str]] = []  # (id, destinatario)
        sin_match: list[str] = []
        conteo_por_patron: dict[str, int] = {label: 0 for _, _, label in _PATRONES}
        ejemplos_por_patron: dict[str, list[tuple[object, str, str]]] = {
            label: [] for _, _, label in _PATRONES
        }

        for row in rows:
            dest = extraer_destinatario(row.descripcion or "")
            if dest is not None:
                actualizaciones.append((row.id, dest))
                # Track which pattern matched for the report
                desc = (row.descripcion or "").strip()
                for patron, _grupo, label in _PATRONES:
                    if patron.match(desc):
                        conteo_por_patron[label] += 1
                        if len(ejemplos_por_patron[label]) < 3:
                            ejemplos_por_patron[label].append((row.id, desc, dest))
                        break
            else:
                sin_match.append(row.descripcion or "")

        # Report
        print(f"\nCandidatos (tipo=automatico, destinatario IS NULL): {total_candidatos}")
        print(
            f"Tendrian destinatario asignado: {len(actualizaciones)}"
            f" ({100 * len(actualizaciones) // max(total_candidatos, 1)}%)"
        )
        print(f"Quedarian NULL (sin patron / skip-list): {len(sin_match)}")

        print("\n=== DESGLOSE POR PATRON ===")
        for _, _, label in _PATRONES:
            n = conteo_por_patron[label]
            if n == 0:
                continue
            print(f"\n  [{label}]: {n} fila(s)")
            for eid, desc, dest in ejemplos_por_patron[label]:
                print(f"    id={eid}  desc={desc!r}  ->  {dest!r}")

        if sin_match:
            print(f"\n=== SIN PATRON ({len(sin_match)} filas) ===")
            for desc in sin_match[:10]:
                print(f"  {desc!r}")
            if len(sin_match) > 10:
                print(f"  ... y {len(sin_match) - 10} mas")

        if not args.apply:
            print(
                "\n[DRY-RUN] No se escribio nada. "
                "Corre con --apply para persistir."
            )
            return

        # Apply — transaction is already open (engine.begin())
        for eid, dest in actualizaciones:
            conn.execute(
                text(
                    "UPDATE egresos "
                    "SET destinatario = :dest "
                    "WHERE id = :eid AND destinatario IS NULL"
                ),
                {"dest": dest, "eid": eid},
            )

        print(f"\n[APPLY] {len(actualizaciones)} egresos actualizados.")


if __name__ == "__main__":
    main()
